---
# Variable configuration.
- name: Include variable configuration
  ansible.builtin.include_tasks: variables.yml

# Setup/install tasks.
- name: Include setup tasks for RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include setup tasks for Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include setup tasks for ArchLinux
  ansible.builtin.include_tasks: setup-ArchLinux.yml
  when: ansible_os_family == 'ArchLinux'

- name: Check if MySQL packages were installed
  ansible.builtin.set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- name: Include MySQL configuration tasks
  ansible.builtin.include_tasks: configure.yml

- name: Include MySQL secure installation tasks
  ansible.builtin.include_tasks: secure-installation.yml

- name: Include database configuration tasks
  ansible.builtin.include_tasks: databases.yml

- name: Include user configuration tasks
  ansible.builtin.include_tasks: users.yml

- name: Include replication configuration tasks
  ansible.builtin.include_tasks: replication.yml